version: "3"
services:
  mongodb:
    image: mongo:5.0.5
    ports:
      - "27017:27017"
      
  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins-instance
    ports:
      - "8080:8080"
    volumes:
      - ./volume/jenkins-data:/var/jenkins_home
    restart: always

volumes:
  jenkins-data:
  jenkins-builds: